# Site settings
title: Charles Dungy
name: Charles Dungy
email: charlesdungy [at] gmail [dot] com
contact: Contact
description: I'm Charles Dungy, a software developer, living in Raleigh, North Carolina.
baseurl: ''
url: ''
twitter_username: charlesdungy
github_username: charlesdungy
linkedin_username: charlesdungy
rss: RSS
show_excerpts: true
copyright: Charles Dungy

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Items to ignore
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - commands.txt