# Site settings
title: Charles Dungy
name: Charles Dungy
email: todo@todo.com
contact: Contact
description: I'm Charles Dungy, a software developer, living in Raleigh, North Carolina.
baseurl: ''
url: ''
twitter_username: charlesdungy
github_username: charlesdungy
linkedin_username: charlesdungy
rss: RSS

# Build settings
theme: minima
plugins:
  - jekyll-feed
